# This workflow is used to run test for a dotnet project.
# The definitaion is referenced from: https://github.com/actions/setup-dotnet
name: Run tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
    - run: dotnet test